### PR TITLE
Disable upload button during uploads 

### LINKED ISSUE #160: media browser: you can upload a file "too early"
This will fail:

1. media browser
2. click upload
3. browse for image
4. click upload when you've selected an image

This will succeed:

1. media browser
2. click upload
3. browse for image
4. wait for your filename to show on the page after selecting an image
5. click upload

### PR DESCRIPTION
**Pull request by arush0311**
Fixes #160

### CODE REVIEW

**Comment by arush0311** [comment]
@pomax. Does this work? I overrode upload.html and upload.js from file browser. I think we should define a custom comment tag for overridden content?

**Comment by Pomax** [comment]
Custom comment is a great idea, we already do this in https://github.com/mozilla/network-api/blob/master/app/networkapi/static/js/admin/page_tree.js but it'll be good to settle on a documented format. I've filed #236 in which I recommend we use `override: start` as  code comment prefix and `override: end` as code comment suffix around blocks of code we modify, as well as saying that in addition to the "start" there should be code comments that explain the modification and point to the issue that is the primary driver for introducing that change to the codebase.

File: app/networkapi/static/js/filebrowser/upload.js [hunk 1]
```diff
@@ -132,19 +138,24 @@
                         .data('selectedFile', null);
                 }
 
+                // override: start #160
                 var results = form.find('.file-input-result.selected');
                 if(results.length==0) {
```
Comment (Pomax) [inline app/networkapi/static/js/filebrowser/upload.js]: note that in Javascript `==` is only equivalence, not identity, so you almost always want to use `===`  unless you really know why you're using `==`

File: app/networkapi/templates/filebrowser/upload.html [hunk 2]
```diff
@@ -19,7 +19,12 @@
 {% block javascripts %}
     {{ block.super }}
     <script type="text/javascript" src="../../jsi18n/"></script>
+
+    <!-- override: start #160 -->
+    <!-- <script type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}js/upload.js"></script> -->
     <script type="text/javascript" src="{% static 'js/filebrowser/upload.js' %}"></script>
```
Comment (Pomax) [inline app/networkapi/templates/filebrowser/upload.html]: since this is used in lots of other places, too, better to replace those `'` quotes around the static tag with `"`, to keep the template code uniform.

File: app/networkapi/templates/filebrowser/upload.html [hunk 3]
```diff
@@ -101,10 +106,15 @@
             <p class="deletelink-box">
                 <a class="deletelink" href="javascript://">{% trans "Clear Queue" %}</a>
             </p>
+
+            <!-- override: start #160 -->
+            <!-- <input class="default" type="submit" name="_save" value='{% trans "Upload" %}' /> -->
```
Comment (Pomax) [inline app/networkapi/templates/filebrowser/upload.html]: it's fine to do this on the same line instead of duplicating just to add an id attribute.

File: app/networkapi/static/js/filebrowser/upload.js (hunk 1 above)
Comment (arush0311) [inline app/networkapi/static/js/filebrowser/upload.js]: sorry just out of practice!

**Comment by arush0311** [comment]
@pomax, I am beginning to think its not the solution here, what if user upload a second file? the upload button would work in that case since there is one selected file.
Can you confirm that this works? I cannot duplicate the delay on my machine

**Comment by arush0311** [comment]
@Pomax This should be fixed now!

**Comment by Pomax** [comment]
Nice, this works really well now.
